spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: order
  datasource:
    url: jdbc:postgresql://${url}/ddang_logistics
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: ${redis-url}
      port: ${redis-port}
      username: ${redis-username}
      password: ${redis-password}


  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true  # 서킷 브레이커 헬스체크 활성화
        sliding-window-type: COUNT_BASED  # 슬라이딩 윈도우 타입 (카운트 기반)
        sliding-window-size: 5            # 슬라이딩 윈도우 크기 (5번의 호출)
        minimum-number-of-calls: 5         # 서킷을 열기 위한 최소 호출 수
        slow-call-rate-threshold: 100     # 느린 호출을 실패로 간주할 비율 (100%)
        slow-call-duration-threshold: 60s # 느린 호출의 기준 시간 (60초)
        failure-rate-threshold: 50        # 서킷을 열기 위한 실패율 (50%)
        permitted-number-of-calls-in-half-open-state: 3  # Half-Open 상태에서 허용할 호출 수
        wait-duration-in-open-state: 20s  # 서킷이 열린 상태로 유지될 시간 (20초)
    instances:
      deliveryService:
        base-config: default
      companyService:
        base-config: default # 여기서 커스텀 가능
      hubService:
        base-config: default # 커스텀 가능
    circuit-breaker-aspect-order: 1
  retry:
    configs:
      default:
        max-attempts: 3 # 3번 재시도
        wait-duration: 1000ms # 재시도 간격 1초
    instances:
      deliveryServiceRetry:
        base-config: default
    retry-aspect-order: 2





eureka:
  client:
    service-url:
      defaultZone: http://server:19090/eureka/

server:
  jwt:
    access-expiration: 3600000
    secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1
    internal-secret-key: 45c7553fdd3c31912b36e569f8e26a4218051ef3709bf4ba16ec9c8d2ba14d535ce63db771f0a7b899b53a3d6f33f8dda7c6c6b1fb35c99d5bb9e93122f82a4b
  port: 19095
management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"


  tracing:
    sampling:
      probability: 1.0


springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /orders/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  remove-broken-reference-definitions: false