spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: gateway
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

  redis:
    host: ${redis-url}
    port: ${redis-port}

server:
  port: 19091

  jwt:
    access-expiration: 3600000
    secret-key: ${jwt-secret-key}
