spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: gateway
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

server:
  port: 19091

  jwt:
    access-expiration: 3600000
    secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1
    internal-secret-key: 45c7553fdd3c31912b36e569f8e26a4218051ef3709bf4ba16ec9c8d2ba14d535ce63db771f0a7b899b53a3d6f33f8dda7c6c6b1fb35c99d5bb9e93122f82a4b



logging:
  level:
    org.springframework.cloud.gateway: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      url: /auths/v3/api-docs
      name: auth
    urls[1]:
      url: /orders/v3/api-docs
      name: orders
    urls[2]:
      url: /companies/v3/api-docs
      name: companies
    urls[3]:
      url: /hubs/v3/api-docs
      name: hubs
    urls[4]:
      url: /deliveries/v3/api-docs
      name: deliveries
    use-root-path: true
  remove-broken-reference-definitions: false

