spring:
  application:
    name: ai
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${PROJECT_ID}
          location: asia-northeast3

google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

weather:
  api-key: ${WEATHER_API_KEY}

server:
  port: 19097
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

service:
  jwt:
    access-expiration: 3600000
    secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1
    internal-secret-key: ${INTERNAL_SECRET_KEY}

