spring:
  application:
    name: ai
  datasource:
    url: jdbc:mysql://${url}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: ${redis-url}
      port: ${redis-port}
      username: ${redis-username}
      password: ${redis-password}

server:
  port: 19097
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${secret-key}

gemini:
  api:
    key: ${gemini}
