spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth

  data:
    redis:
      host: ${redis-url}
      port: ${redis-port}

server:
  port: 19092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

service:
  jwt:
    access-expiration: ${expiration-time}
    secret-key: ${jwt-secret-key}
